---
title: "Demo Document"
author: "Author's Name"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: no
  html_document:
    theme: cerulean
    toc: yes
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Set up the environment
library(knitr)
opts_chunk$set(cache.path='cache/', fig.path='img/', cache=F, tidy=T, fig.keep='high', echo=F, dpi=100, warnings=F, message=F, comment=NA, warning=F, results='as.is', fig.width = 10, fig.height = 6) #out.width=700, 
library(pander)
panderOptions('table.split.table', Inf)
set.seed(1)
library(dplyr)
options(stringsAsFactors = FALSE)
```

```{r libraries}
library(purrr)
library(openxlsx)
# devtools::install_github("alastairrushworth/inspectdf")
library(inspectdf)
```

# Settings

```{r settings}
# establish the location of the GWAS datasets
# data_dir <- "/home/stilianoudakisc/DREAM_module/4_gwas_datasets/gene_scores/"
data_dir <- "/Users/mdozmorov/Documents/Data/DREAM_module/4_gwas_datasets/gene_scores/"
# Cutoffs
pvalue_cutoff_max <- 5E-2 # Lower bound of p-value cutoff
pvalue_cutoff_min <- 5E-8 # Higher bound of p-value cutoff
```

# Load data

Full gene scores

```{r}
# establish complete path to read in each GWAS dataset
data_file <- file.path(data_dir,list.files(data_dir))

# establish the total number of GWAS datasets to loop through (should be 180)
data_length <- length(data_file)

# establish an empty list to fill in necessary parts from each GWAS dataset
gene_data_list <- vector(mode = "list", length = data_length)

for(i in 1:data_length){
  # print(list.files(data_dir)[i])
  data <- read.table(data_file[i], header = TRUE) 
  
  # extract only gene name and p-value
  data <- data %>% dplyr::select(gene_id, pvalue) # %>% dplyr::arrange(pvalue)

  # remove .txt from the name of the GWAS dataset
  colnames(data) <- c("gene_id", gsub(".txt", "", basename(data_file[i])))

  # Save the current data
  gene_data_list[[i]] <- data
}

# Perform Recursive full joins on the list of datasets to merge all datasets (with complete list of genes) into one
gene_data_full <- gene_data_list %>% purrr::reduce(dplyr::full_join, by = "gene_id") # join_all(gene_data_list, by='gene_id', type='full')

# remove the ".sum.genescores" part common to all GWAS dataset names
names(gene_data_full) <- gsub(".sum.genescores.gz", "", names(gene_data_full), fixed = TRUE)
gene_data_full[1:5, 1:5]
```

# Exploring global cutoffs

```{r}
# Vectors to store p-value cutoffs and medians
pvalue_cutoffs    <- c()
num_genes_medians <- c()
# Get median number of genes depending on the p-value cutoff
for (pvalue_cutoff in seq(pvalue_cutoff_min, pvalue_cutoff_max, by = 5E-3)) {
  # Median at a given cutoff
  num_genes_median <- gene_data_full %>% dplyr::select(-gene_id) %>% sapply(., function(x) sum(x < pvalue_cutoff, na.rm = TRUE)) %>% median()
  # Save the results
  pvalue_cutoffs    <- c(pvalue_cutoffs, pvalue_cutoff)
  num_genes_medians <- c(num_genes_medians, num_genes_median)
}
# Quick visualization
plot(num_genes_medians, pvalue_cutoffs)
# View(cbind(num_genes_medians, pvalue_cutoffs))
# Select cutoff
pvalue_cutoff <- 0.001
# Number of genes for each disease using this cutoff
num_genes <- gene_data_full %>% dplyr::select(-gene_id) %>% sapply(., function(x) sum(x < pvalue_cutoff, na.rm = TRUE))
# Add column names
names(num_genes) <- gene_data_full %>% dplyr::select(-gene_id) %>% colnames() 
# Largest/smallest GWASs
num_genes %>% sort(decreasing = TRUE) %>% head
num_genes %>% sort(decreasing = FALSE) %>% head
# Quick summary statistics
summary(num_genes)
hist(num_genes)
```

# Exploring per category cutoffs

```{r}
mtx <- read.xlsx("https://www.biorxiv.org/content/biorxiv/early/2019/01/28/265553/DC1/embed/media-1.xlsx", startRow = 8)
mtx$Data.file <- gsub(".txt.gz", "", mtx$Data.file)
# Attach num_genes
# inspectdf
mtx %>% inspect_types()
mtx_cat <- mtx %>% inspect_cat()
mtx_cat
mtx %>% dplyr::select(GWAS.set, Category, Trait.type, GWAS.trait) %>% inspect_cat() %>% show_plot()
mtx_cat$levels$Category
```

```{r}
mtx_subset <- mtx %>% dplyr::filter(Category == "Anthropometric")
gene_data_subset <- gene_data_full[, colnames(gene_data_full) %in% mtx_subset$Data.file]
gene_data_subset %>% sapply(., function(x) sum(x < pvalue_cutoff, na.rm = TRUE)) %>% sort(decreasing = TRUE) %>% head
gene_data_subset %>% sapply(., function(x) sum(x < pvalue_cutoff, na.rm = TRUE)) %>% sort(decreasing = FALSE) %>% head
```

Conclusion: There is a big overlap among different GWASs targeting the same trait/disease. Different GWASs differ widely in the number of significant genes. Many diseases/traits are missing. The data does not seem useful.
