---
output:
  word_document:
    reference_docx: /Users/mdozmorov/Documents/Work/presentations/Templates/grant_template/styles.doc/NSF_grant_style.docx
  html_document: default
---

Dear Dr. Talbot,

This submission is the full revision of the manuscript BINF-D-19-01133. The title of the revised manuscript is "A Method for Estimating Coherence of Molecular Mechanisms In Major Human Disease and Traits". This manuscript will be of interest to the network analysis community working with the analysis of molecular networks.

All comments raised during previous revisions have been addressed. The point-by-point response is submitted as a supplementary file.

The brief overview of our revised work are:

- Focus on a novel method for estimating and comparing the coherence of molecular-interaction networks. This method is independent of the size of molecular networks, allowing for comparing coherences across phenotype-specific networks of different sizes. The high coherence of a molecular network may inform about the therapeutically targetable molecular mechanisms.
- Coherence estimation and comparison across 116 phenotype-specific networks from seven disease- and five trait categories, including the estimation of statistical significance of coherence measures.
- Validation of our approach using different protein-protein interaction (PPI) databases.
- Identification of diseases and traits with high or low coherence. E.g., metabolic diseases and traits showed consistently high coherence, while psychiatric disorders and intelligence-related traits were the least coherent.
- Demonstration that coherence and the commonly used modularity measures capture different network properties.

All data used in the manuscript was sourced from publicly available repositories (GWAScatalog, STRING, and Biogrid PPIs, MSigDb). All code and data needed to reproduce our results are made available on our GitHub repository https://github.com/dozmorovlab/disease_coherence. We also want to assure that this manuscript is not being considered for publication elsewhere.

With our best regards,  
On behalf of all authors,

Mikhail Dozmorov, Ph.D., Blick scholar  
Assistant Professor,  Department of Biostatistics 
Affiliate, Department of Pathology  
Virginia Commonwealth University  
One Capitol Square, room 738  
830 East Main Street  
Richmond,  Virginia  23298  
e-mail:  mikhail.dozmorov@vcuhealth.org  
Phone: 804-827-2055  
